# Generated by Django 3.2.6 on 2021-08-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_subject',
            unique_together={('sub_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='waiting_list',
            unique_together={('sub_id', 'user_id')},
        ),
    ]
